// react/components/app-header.tsx
"use client"

import Link from "next/link"
import { Database, CreditCard, Users, Sparkles } from "lucide-react"
import { Button } from "@/components/ui/button"
import { UserButton, SignedIn, SignedOut, SignInButton } from "@clerk/nextjs"
import { useSchematicIsPending } from "@schematichq/schematic-react"
import { CreditsBadge } from "@/components/credits-badge"

export function AppHeader() {
  const isPending = useSchematicIsPending()
  return (
    <header className="border-b border-border">
      <div className="flex items-center justify-between px-6 py-4">
        <div className="flex items-center gap-8">
          <Link href="/" className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-accent">
              <Sparkles className="h-4 w-4 text-accent-foreground" />
            </div>
            <span className="text-lg font-semibold">DashAI</span>
          </Link>
          <nav className="flex items-center gap-6">
            <Link href="/" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
              Builder
            </Link>
            <Link
              href="/team"
              className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              <Users className="h-4 w-4" />
              Team
            </Link>
            <Link
              href="/data-sources"
              className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              <Database className="h-4 w-4" />
              Data Sources
            </Link>
          </nav>
        </div>
        <div className="flex items-center gap-4">
          {isPending && (
            <span className="text-xs text-muted-foreground animate-pulse">Loading...</span>
          )}
          <CreditsBadge />
          <Link href="/pricing">
            <Button variant="ghost" size="sm" className="text-muted-foreground">
              Pricing
            </Button>
          </Link>
          <Link href="/plan">
            <Button variant="outline" size="sm" className="gap-2 bg-transparent">
              <CreditCard className="h-4 w-4" />
              Plan
            </Button>
          </Link>
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
        </div>
      </div>
    </header>
  )
}

// vue/src/components/AppHeader.vue
<script setup lang="ts">
import { Sparkles, Users, Database, CreditCard } from 'lucide-vue-next'
import { useSchematicIsPending } from '@schematichq/schematic-vue'
import CreditsBadge from '@/components/CreditsBadge.vue'

const isPending = useSchematicIsPending()
</script>

<template>
  <header class="border-b border-border">
    <div class="flex items-center justify-between px-6 py-4">
      <div class="flex items-center gap-8">
        <RouterLink to="/" class="flex items-center gap-2">
          <div class="flex h-8 w-8 items-center justify-center rounded-lg bg-accent">
            <Sparkles :size="16" class="text-accent-foreground" />
          </div>
          <span class="text-lg font-semibold">DashAI</span>
        </RouterLink>
        <nav class="flex items-center gap-6">
          <RouterLink to="/" class="text-sm text-muted-foreground hover:text-foreground transition-colors">
            Builder
          </RouterLink>
          <RouterLink
            to="/team"
            class="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <Users :size="16" />
            Team
          </RouterLink>
          <RouterLink
            to="/data-sources"
            class="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <Database :size="16" />
            Data Sources
          </RouterLink>
        </nav>
      </div>
      <div class="flex items-center gap-4">
        <span v-if="isPending" class="text-xs text-muted-foreground animate-pulse">
          Loading...
        </span>
        <CreditsBadge />
        <RouterLink to="/pricing">
          <button class="px-3 py-1.5 text-sm text-muted-foreground hover:text-foreground hover:bg-muted rounded-md transition-colors">
            Pricing
          </button>
        </RouterLink>
        <RouterLink to="/plan">
          <button class="flex items-center gap-2 px-3 py-1.5 text-sm border border-border rounded-md bg-transparent hover:bg-muted transition-colors">
            <CreditCard :size="16" />
            Plan
          </button>
        </RouterLink>
      </div>
    </div>
  </header>
</template>
