// angular/src/app/pages/team/team.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { AsyncPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { SchematicService, CheckFlagReturn } from '@schematichq/schematic-angular';
import { Observable } from 'rxjs';
import {
  SchematicApiService,
  TeamMember,
} from '../../services/schematic-api.service';

/**
 * OBSERVABLE PATTERN: Uses async pipe for the user-seat entitlement.
 */
@Component({
  selector: 'app-team',
  imports: [AsyncPipe, FormsModule],
  template: `
    <div class="min-h-screen flex flex-col">
      <main class="flex-1 p-6">
        <div class="max-w-4xl mx-auto space-y-8">
          <div>
            <h1 class="text-2xl font-bold mb-1">Team</h1>
            <p class="text-muted-foreground">
              Manage who has access to your dashboards
            </p>
          </div>

          @if (entitlement$ | async; as ent) {
            @if (ent.value === false) {
              <div
                class="rounded-lg border border-violet-800/80 bg-violet-950/40 p-4 flex items-center justify-between"
              >
                <div class="flex items-center gap-3">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="h-5 w-5 text-violet-400 shrink-0"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <circle cx="12" cy="12" r="10" />
                    <line x1="12" x2="12" y1="8" y2="12" />
                    <line x1="12" x2="12.01" y1="16" y2="16" />
                  </svg>
                  <div>
                    <p class="text-sm font-medium text-violet-100">
                      Seat limit reached
                    </p>
                    <p class="text-xs text-violet-300">
                      Upgrade your plan to add more team members
                    </p>
                  </div>
                </div>
                <a
                  href="/pricing"
                  class="inline-flex items-center gap-2 rounded-md bg-violet-600 hover:bg-violet-700 text-white text-sm font-medium h-9 px-3 shrink-0"
                >
                  Upgrade
                </a>
              </div>
            }

            <div class="rounded-lg border border-border bg-card">
              <div class="flex items-center justify-between p-4 border-b border-border">
                <div>
                  <h3 class="text-lg font-semibold">Team Members</h3>
                  <p class="text-sm text-muted-foreground">
                    Invite and manage your team
                  </p>
                </div>
                @if (!showAddForm()) {
                  <button
                    (click)="showAddForm.set(true)"
                    [disabled]="ent.value === false"
                    class="inline-flex items-center gap-2 rounded-md bg-primary text-primary-foreground text-sm font-medium h-9 px-3 disabled:opacity-50 disabled:cursor-not-allowed"
                    [title]="
                      ent.value === false
                        ? 'Seat limit reached'
                        : 'Invite a new team member'
                    "
                  >
                    + Invite Member
                  </button>
                }
              </div>
              <div class="p-4">
                @if (showAddForm()) {
                  <div class="mb-4 p-4 rounded-lg border border-border bg-muted/50">
                    <div class="flex items-center justify-between mb-4">
                      <h3 class="text-sm font-medium">Add Team Member</h3>
                      <button
                        (click)="cancelAdd()"
                        class="h-6 w-6 inline-flex items-center justify-center rounded hover:bg-muted"
                      >
                        X
                      </button>
                    </div>
                    <div class="space-y-3">
                      <input
                        type="text"
                        placeholder="Name"
                        [(ngModel)]="newMember.name"
                        class="w-full px-3 py-2 text-sm rounded-md border border-border bg-background"
                      />
                      <input
                        type="email"
                        placeholder="Email"
                        [(ngModel)]="newMember.email"
                        class="w-full px-3 py-2 text-sm rounded-md border border-border bg-background"
                      />
                      <select
                        [(ngModel)]="newMember.role"
                        class="w-full px-3 py-2 text-sm rounded-md border border-border bg-background"
                      >
                        <option value="Admin">Admin</option>
                        <option value="Editor">Editor</option>
                        <option value="Viewer">Viewer</option>
                      </select>
                      <div class="flex gap-2">
                        <button
                          (click)="handleAddMember()"
                          [disabled]="
                            isSubmitting() || !newMember.name || !newMember.email
                          "
                          class="flex-1 inline-flex items-center justify-center rounded-md bg-primary text-primary-foreground text-sm font-medium h-9 px-3 disabled:opacity-50"
                        >
                          {{ isSubmitting() ? 'Adding...' : 'Add Member' }}
                        </button>
                        <button
                          (click)="cancelAdd()"
                          class="inline-flex items-center justify-center rounded-md border border-border text-sm font-medium h-9 px-3 hover:bg-muted/50"
                        >
                          Cancel
                        </button>
                      </div>
                    </div>
                  </div>
                }

                <div class="space-y-4">
                  @if (isLoading()) {
                    <p class="text-sm text-muted-foreground">
                      Loading team members...
                    </p>
                  } @else if (teamMembers().length === 0) {
                    <p class="text-sm text-muted-foreground">
                      No team members yet. Add one to get started.
                    </p>
                  } @else {
                    @for (member of teamMembers(); track member.id) {
                      <div
                        class="flex items-center justify-between p-3 rounded-lg border border-border"
                      >
                        <div class="flex items-center gap-3">
                          <div
                            class="h-9 w-9 rounded-full bg-accent flex items-center justify-center text-accent-foreground text-sm font-medium"
                          >
                            {{ member.initials }}
                          </div>
                          <div>
                            <p class="text-sm font-medium">{{ member.name }}</p>
                            <p class="text-xs text-muted-foreground">
                              {{ member.email }}
                            </p>
                          </div>
                        </div>
                        <div class="flex items-center gap-3">
                          <span
                            class="inline-flex items-center rounded-full bg-secondary px-2.5 py-0.5 text-xs font-medium text-secondary-foreground"
                          >
                            {{ member.role }}
                          </span>
                          <button
                            (click)="handleDeleteMember(member.id)"
                            class="h-8 w-8 inline-flex items-center justify-center rounded text-muted-foreground hover:text-destructive"
                          >
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              class="h-4 w-4"
                              viewBox="0 0 24 24"
                              fill="none"
                              stroke="currentColor"
                              stroke-width="2"
                              stroke-linecap="round"
                              stroke-linejoin="round"
                            >
                              <path d="M3 6h18" />
                              <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
                              <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
                            </svg>
                          </button>
                        </div>
                      </div>
                    }
                  }
                </div>
                <div class="mt-4 pt-4 border-t border-border">
                  <p class="text-sm text-muted-foreground">
                    <span class="font-medium text-foreground"
                      >{{ ent.featureUsage }} of
                      {{ ent.featureAllocation }}</span
                    >
                    seats used on your current plan
                  </p>
                </div>
              </div>
            </div>
          }
        </div>
      </main>
    </div>
  `,
})
export class TeamComponent implements OnInit {
  private schematic = inject(SchematicService);
  private api = inject(SchematicApiService);

  // Observable pattern: entitlement via async pipe
  entitlement$: Observable<CheckFlagReturn> =
    this.schematic.entitlement$('user-seat');

  teamMembers = signal<TeamMember[]>([]);
  isLoading = signal(true);
  showAddForm = signal(false);
  isSubmitting = signal(false);
  newMember = { name: '', email: '', role: 'Viewer' };

  ngOnInit(): void {
    this.api.getUsers().subscribe({
      next: (users) => {
        this.teamMembers.set(users);
        this.isLoading.set(false);
      },
      error: (err) => {
        console.error('Error fetching users:', err);
        this.isLoading.set(false);
      },
    });
  }

  handleAddMember(): void {
    if (!this.newMember.name || !this.newMember.email) return;

    this.isSubmitting.set(true);
    this.api.addUser(this.newMember).subscribe({
      next: (user) => {
        this.teamMembers.update((members) => [...members, user]);
        this.cancelAdd();
        this.isSubmitting.set(false);
      },
      error: (err) => {
        console.error('Error adding member:', err);
        alert(err.error?.message || 'Failed to add member');
        this.isSubmitting.set(false);
      },
    });
  }

  handleDeleteMember(id: string): void {
    if (!confirm('Are you sure you want to remove this team member?')) return;

    this.api.deleteUser(id).subscribe({
      next: () => {
        this.teamMembers.update((members) => members.filter((m) => m.id !== id));
      },
      error: (err) => {
        console.error('Error deleting member:', err);
        alert(err.error?.message || 'Failed to delete member');
      },
    });
  }

  cancelAdd(): void {
    this.showAddForm.set(false);
    this.newMember = { name: '', email: '', role: 'Viewer' };
  }
}

// app/team/page.tsx
"use client"

import { useState, useEffect } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Plus, Trash2, X, AlertCircle, ArrowUp } from "lucide-react"
import { useSchematicEntitlement } from "@schematichq/schematic-react"

interface TeamMember {
  id: string
  name: string
  email: string
  role: string
  initials: string
}

export default function TeamPage() {
  const [teamMembers, setTeamMembers] = useState<TeamMember[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [showAddForm, setShowAddForm] = useState(false)
  const [newMember, setNewMember] = useState({ name: "", email: "", role: "Viewer" })
  const [isSubmitting, setIsSubmitting] = useState(false)
  
  // Get seat count entitlement from Schematic
  const { value, featureAllocation: allocation, featureUsage: usage } = useSchematicEntitlement("user-seat")

  const fetchUsers = async () => {
    try {
      const response = await fetch("/api/users")
      if (response.ok) {
        const users = await response.json()
        setTeamMembers(users)
      }
    } catch (error) {
      console.error("Error fetching users:", error)
    } finally {
      setIsLoading(false)
    }
  }

  useEffect(() => {
    fetchUsers()
  }, [])

  const handleAddMember = async () => {
    if (!newMember.name || !newMember.email) {
      return
    }

    setIsSubmitting(true)
    try {
      const response = await fetch("/api/users", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(newMember),
      })

      if (response.ok) {
        const addedUser = await response.json()
        setTeamMembers([...teamMembers, addedUser])
        setNewMember({ name: "", email: "", role: "Viewer" })
        setShowAddForm(false)
      } else {
        const error = await response.json()
        alert(error.message || "Failed to add member")
      }
    } catch (error) {
      console.error("Error adding member:", error)
      alert("Failed to add member")
    } finally {
      setIsSubmitting(false)
    }
  }

  const handleDeleteMember = async (id: string) => {
    if (!confirm("Are you sure you want to remove this team member?")) {
      return
    }

    try {
      const response = await fetch(`/api/users?id=${id}`, {
        method: "DELETE",
      })

      if (response.ok) {
        setTeamMembers(teamMembers.filter((member) => member.id !== id))
      } else {
        const error = await response.json()
        alert(error.message || "Failed to delete member")
      }
    } catch (error) {
      console.error("Error deleting member:", error)
      alert("Failed to delete member")
    }
  }

  return (
    <div className="min-h-screen flex flex-col">
      <main className="flex-1 p-6">
        <div className="max-w-4xl mx-auto space-y-8">
          <div>
            <h1 className="text-2xl font-bold mb-1">Team</h1>
            <p className="text-muted-foreground">Manage who has access to your dashboards</p>
          </div>

          {value === false && (
            <div className="rounded-lg border border-violet-200 dark:border-violet-800/80 bg-violet-50/80 dark:bg-violet-950/40 p-4 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <AlertCircle className="h-5 w-5 text-violet-600 dark:text-violet-400 shrink-0" />
                <div>
                  <p className="text-sm font-medium text-violet-900 dark:text-violet-100">Seat limit reached</p>
                  <p className="text-xs text-violet-700 dark:text-violet-300">Upgrade your plan to add more team members</p>
                </div>
              </div>
              <Button
                size="sm"
                className="gap-2 bg-violet-600 hover:bg-violet-700 text-white border-0 shrink-0"
                onClick={() => (window.location.href = "/pricing")}
              >
                <ArrowUp className="h-4 w-4" />
                Upgrade
              </Button>
            </div>
          )}

          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <div>
                <CardTitle className="text-lg">Team Members</CardTitle>
                <CardDescription>Invite and manage your team</CardDescription>
              </div>
              {!showAddForm && (
                <Button 
                  size="sm" 
                  className="gap-2 disabled:cursor-not-allowed disabled:opacity-60" 
                  onClick={() => setShowAddForm(true)}
                  disabled={value === false}
                  title={value === false ? "Seat limit reached" : "Invite a new team member"}
                >
                  <Plus className="h-4 w-4" />
                  Invite Member
                </Button>
              )}
            </CardHeader>
            <CardContent>
              {showAddForm && (
                <div className="mb-4 p-4 rounded-lg border border-border bg-muted/50">
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="text-sm font-medium">Add Team Member</h3>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-6 w-6"
                      onClick={() => {
                        setShowAddForm(false)
                        setNewMember({ name: "", email: "", role: "Viewer" })
                      }}
                    >
                      <X className="h-4 w-4" />
                    </Button>
                  </div>
                  <div className="space-y-3">
                    <input
                      type="text"
                      placeholder="Name"
                      value={newMember.name}
                      onChange={(e) => setNewMember({ ...newMember, name: e.target.value })}
                      className="w-full px-3 py-2 text-sm rounded-md border border-border bg-background"
                    />
                    <input
                      type="email"
                      placeholder="Email"
                      value={newMember.email}
                      onChange={(e) => setNewMember({ ...newMember, email: e.target.value })}
                      className="w-full px-3 py-2 text-sm rounded-md border border-border bg-background"
                    />
                    <Select
                      value={newMember.role}
                      onValueChange={(value) => setNewMember({ ...newMember, role: value })}
                    >
                      <SelectTrigger className="w-full">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="Admin">Admin</SelectItem>
                        <SelectItem value="Editor">Editor</SelectItem>
                        <SelectItem value="Viewer">Viewer</SelectItem>
                      </SelectContent>
                    </Select>
                    <div className="flex gap-2">
                      <Button
                        size="sm"
                        onClick={handleAddMember}
                        disabled={isSubmitting || !newMember.name || !newMember.email}
                        className="flex-1"
                      >
                        {isSubmitting ? "Adding..." : "Add Member"}
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => {
                          setShowAddForm(false)
                          setNewMember({ name: "", email: "", role: "Viewer" })
                        }}
                      >
                        Cancel
                      </Button>
                    </div>
                  </div>
                </div>
              )}

              <div className="space-y-4">
                {isLoading ? (
                  <p className="text-sm text-muted-foreground">Loading team members...</p>
                ) : teamMembers.length === 0 ? (
                  <p className="text-sm text-muted-foreground">No team members yet. Add one to get started.</p>
                ) : (
                  teamMembers.map((member) => (
                    <div
                      key={member.id}
                      className="flex items-center justify-between p-3 rounded-lg border border-border"
                    >
                      <div className="flex items-center gap-3">
                        <Avatar className="h-9 w-9">
                          <AvatarFallback className="bg-accent text-accent-foreground text-sm">
                            {member.initials}
                          </AvatarFallback>
                        </Avatar>
                        <div>
                          <p className="text-sm font-medium">{member.name}</p>
                          <p className="text-xs text-muted-foreground">{member.email}</p>
                        </div>
                      </div>
                      <div className="flex items-center gap-3">
                        <Badge variant="secondary" className="text-xs">
                          {member.role}
                        </Badge>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-8 w-8 text-muted-foreground hover:text-destructive"
                          onClick={() => handleDeleteMember(member.id)}
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>
                  ))
                )}
              </div>
              <div className="mt-4 pt-4 border-t border-border">
                <p className="text-sm text-muted-foreground">
                  <span className="font-medium text-foreground">{usage} of {allocation}</span> seats used on your current plan
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}
