// vue/src/components/GeneratedDashboard.vue
<script setup lang="ts">
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  ArcElement,
  Filler,
  Tooltip,
  Legend,
} from 'chart.js'
import { Line, Bar, Doughnut } from 'vue-chartjs'
import {
  TrendingUp,
  TrendingDown,
  Users,
  DollarSign,
  ShoppingCart,
  Activity,
} from 'lucide-vue-next'

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  ArcElement,
  Filler,
  Tooltip,
  Legend,
)

// Shared chart options for dark theme
const baseOptions = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: { display: false },
    tooltip: {
      backgroundColor: 'oklch(0.16 0 0)',
      borderColor: 'oklch(0.28 0 0)',
      borderWidth: 1,
      titleColor: '#fff',
      bodyColor: '#aaa',
      padding: 8,
      cornerRadius: 8,
    },
  },
  scales: {
    x: {
      grid: { color: '#333' },
      ticks: { color: '#666', font: { size: 12 } },
      border: { display: false },
    },
    y: {
      grid: { color: '#333' },
      ticks: { color: '#666', font: { size: 12 } },
      border: { display: false },
    },
  },
}

// Revenue vs Target (Area chart = Line with fill)
const revenueData = {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
  datasets: [
    {
      label: 'Target',
      data: [4000, 4200, 4400, 4600, 4800, 5000, 5200, 5400],
      borderColor: '#404040',
      backgroundColor: 'rgba(64, 64, 64, 0.3)',
      fill: true,
      tension: 0.4,
      pointRadius: 0,
    },
    {
      label: 'Revenue',
      data: [4200, 3800, 5100, 4900, 6200, 5800, 7100, 6800],
      borderColor: '#6366f1',
      backgroundColor: 'rgba(99, 102, 241, 0.5)',
      fill: true,
      tension: 0.4,
      pointRadius: 0,
    },
  ],
}

// User Activity (Bar chart)
const userActivityData = {
  labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  datasets: [
    {
      label: 'Active Users',
      data: [2400, 1398, 9800, 3908, 4800, 3800, 4300],
      backgroundColor: '#22c55e',
      borderRadius: 4,
    },
    {
      label: 'New Users',
      data: [400, 300, 500, 480, 380, 430, 340],
      backgroundColor: '#6366f1',
      borderRadius: 4,
    },
  ],
}

// Traffic Sources (Doughnut chart)
const trafficData = {
  labels: ['Organic', 'Direct', 'Referral', 'Social'],
  datasets: [
    {
      data: [42, 28, 18, 12],
      backgroundColor: ['#6366f1', '#22c55e', '#f59e0b', '#ec4899'],
      borderWidth: 0,
    },
  ],
}

const doughnutOptions = {
  responsive: true,
  maintainAspectRatio: false,
  cutout: '62%',
  plugins: {
    legend: { display: false },
    tooltip: {
      backgroundColor: 'oklch(0.16 0 0)',
      borderColor: 'oklch(0.28 0 0)',
      borderWidth: 1,
      titleColor: '#fff',
      bodyColor: '#aaa',
      padding: 8,
      cornerRadius: 8,
      callbacks: {
        label: (ctx: { label: string; parsed: number }) => `${ctx.label}: ${ctx.parsed}%`,
      },
    },
  },
}

// Conversion Funnel (Line chart)
const conversionData = {
  labels: ['W1', 'W2', 'W3', 'W4'],
  datasets: [
    {
      label: 'Visitors',
      data: [1200, 1400, 1100, 1600],
      borderColor: '#666',
      tension: 0.4,
      pointRadius: 0,
      borderWidth: 2,
    },
    {
      label: 'Signups',
      data: [120, 150, 98, 180],
      borderColor: '#6366f1',
      tension: 0.4,
      pointRadius: 0,
      borderWidth: 2,
    },
    {
      label: 'Purchases',
      data: [45, 52, 38, 68],
      borderColor: '#22c55e',
      tension: 0.4,
      pointRadius: 0,
      borderWidth: 2,
    },
  ],
}

const trafficLegend = [
  { name: 'Organic', value: 42, color: '#6366f1' },
  { name: 'Direct', value: 28, color: '#22c55e' },
  { name: 'Referral', value: 18, color: '#f59e0b' },
  { name: 'Social', value: 12, color: '#ec4899' },
]
</script>

<template>
  <div class="space-y-6">
    <div class="flex items-center justify-between">
      <div>
        <h2 class="text-xl font-semibold">Generated Dashboard</h2>
        <p class="text-sm text-muted-foreground">Business performance overview</p>
      </div>
      <div class="flex items-center gap-2 text-xs text-muted-foreground">
        <div class="h-2 w-2 rounded-full bg-green-500 animate-pulse" />
        Live data
      </div>
    </div>

    <!-- Metric Cards -->
    <div class="grid grid-cols-4 gap-4">
      <div class="rounded-lg border border-border bg-card p-4">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-xs text-muted-foreground">Total Revenue</p>
            <p class="text-2xl font-bold">$43,900</p>
            <div class="flex items-center gap-1 mt-1">
              <TrendingUp :size="12" class="text-green-500" />
              <span class="text-xs text-green-500">+12.5%</span>
            </div>
          </div>
          <div class="h-10 w-10 rounded-lg bg-accent/20 flex items-center justify-center">
            <DollarSign :size="20" class="text-accent" />
          </div>
        </div>
      </div>
      <div class="rounded-lg border border-border bg-card p-4">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-xs text-muted-foreground">Active Users</p>
            <p class="text-2xl font-bold">8,234</p>
            <div class="flex items-center gap-1 mt-1">
              <TrendingUp :size="12" class="text-green-500" />
              <span class="text-xs text-green-500">+8.2%</span>
            </div>
          </div>
          <div class="h-10 w-10 rounded-lg bg-accent/20 flex items-center justify-center">
            <Users :size="20" class="text-accent" />
          </div>
        </div>
      </div>
      <div class="rounded-lg border border-border bg-card p-4">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-xs text-muted-foreground">Orders</p>
            <p class="text-2xl font-bold">1,429</p>
            <div class="flex items-center gap-1 mt-1">
              <TrendingDown :size="12" class="text-red-500" />
              <span class="text-xs text-red-500">-3.1%</span>
            </div>
          </div>
          <div class="h-10 w-10 rounded-lg bg-accent/20 flex items-center justify-center">
            <ShoppingCart :size="20" class="text-accent" />
          </div>
        </div>
      </div>
      <div class="rounded-lg border border-border bg-card p-4">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-xs text-muted-foreground">Conversion</p>
            <p class="text-2xl font-bold">3.24%</p>
            <div class="flex items-center gap-1 mt-1">
              <TrendingUp :size="12" class="text-green-500" />
              <span class="text-xs text-green-500">+0.4%</span>
            </div>
          </div>
          <div class="h-10 w-10 rounded-lg bg-accent/20 flex items-center justify-center">
            <Activity :size="20" class="text-accent" />
          </div>
        </div>
      </div>
    </div>

    <!-- Charts Row 1 -->
    <div class="grid grid-cols-2 gap-6">
      <div class="rounded-lg border border-border bg-card">
        <div class="p-4 pb-2">
          <h3 class="text-base font-semibold">Revenue vs Target</h3>
          <p class="text-sm text-muted-foreground">Monthly performance comparison</p>
        </div>
        <div class="p-4 h-[250px]">
          <Line :data="revenueData" :options="baseOptions" />
        </div>
      </div>

      <div class="rounded-lg border border-border bg-card">
        <div class="p-4 pb-2">
          <h3 class="text-base font-semibold">User Activity</h3>
          <p class="text-sm text-muted-foreground">Daily active and new users</p>
        </div>
        <div class="p-4 h-[250px]">
          <Bar :data="userActivityData" :options="baseOptions" />
        </div>
      </div>
    </div>

    <!-- Charts Row 2 -->
    <div class="grid grid-cols-3 gap-6">
      <div class="rounded-lg border border-border bg-card">
        <div class="p-4 pb-2">
          <h3 class="text-base font-semibold">Traffic Sources</h3>
          <p class="text-sm text-muted-foreground">Where your visitors come from</p>
        </div>
        <div class="p-4">
          <div class="h-[200px]">
            <Doughnut :data="trafficData" :options="doughnutOptions" />
          </div>
          <div class="grid grid-cols-2 gap-2 mt-4">
            <div
              v-for="item in trafficLegend"
              :key="item.name"
              class="flex items-center gap-2"
            >
              <div
                class="h-2 w-2 rounded-full"
                :style="{ backgroundColor: item.color }"
              />
              <span class="text-xs text-muted-foreground">{{ item.name }}</span>
              <span class="text-xs font-medium ml-auto">{{ item.value }}%</span>
            </div>
          </div>
        </div>
      </div>

      <div class="col-span-2 rounded-lg border border-border bg-card">
        <div class="p-4 pb-2">
          <h3 class="text-base font-semibold">Conversion Funnel</h3>
          <p class="text-sm text-muted-foreground">Weekly visitor to purchase journey</p>
        </div>
        <div class="p-4 h-[200px]">
          <Line :data="conversionData" :options="baseOptions" />
        </div>
      </div>
    </div>
  </div>
</template>

// react/components/generated-dashboard.tsx
"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { ChartContainer } from "@/components/ui/chart"
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  AreaChart,
  Area,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
} from "recharts"
import { TrendingUp, TrendingDown, Users, DollarSign, ShoppingCart, Activity } from "lucide-react"

const revenueData = [
  { month: "Jan", revenue: 4200, target: 4000 },
  { month: "Feb", revenue: 3800, target: 4200 },
  { month: "Mar", revenue: 5100, target: 4400 },
  { month: "Apr", revenue: 4900, target: 4600 },
  { month: "May", revenue: 6200, target: 4800 },
  { month: "Jun", revenue: 5800, target: 5000 },
  { month: "Jul", revenue: 7100, target: 5200 },
  { month: "Aug", revenue: 6800, target: 5400 },
]

const userActivityData = [
  { day: "Mon", active: 2400, new: 400 },
  { day: "Tue", active: 1398, new: 300 },
  { day: "Wed", active: 9800, new: 500 },
  { day: "Thu", active: 3908, new: 480 },
  { day: "Fri", active: 4800, new: 380 },
  { day: "Sat", active: 3800, new: 430 },
  { day: "Sun", active: 4300, new: 340 },
]

const trafficSourceData = [
  { name: "Organic", value: 42, fill: "#6366f1" },
  { name: "Direct", value: 28, fill: "#22c55e" },
  { name: "Referral", value: 18, fill: "#f59e0b" },
  { name: "Social", value: 12, fill: "#ec4899" },
]

const conversionData = [
  { week: "W1", visitors: 1200, signups: 120, purchases: 45 },
  { week: "W2", visitors: 1400, signups: 150, purchases: 52 },
  { week: "W3", visitors: 1100, signups: 98, purchases: 38 },
  { week: "W4", visitors: 1600, signups: 180, purchases: 68 },
]

function CustomTooltip({
  active,
  payload,
  label,
}: { active?: boolean; payload?: Array<{ name: string; value: number; color?: string }>; label?: string }) {
  if (!active || !payload?.length) return null
  return (
    <div className="rounded-lg border border-border/50 bg-background px-3 py-2 text-xs shadow-xl">
      {label && <div className="font-medium mb-1">{label}</div>}
      {payload.map((entry, index) => (
        <div key={index} className="flex items-center gap-2">
          <div className="h-2 w-2 rounded-full" style={{ backgroundColor: entry.color }} />
          <span className="text-muted-foreground">{entry.name}:</span>
          <span className="font-medium">{entry.value?.toLocaleString()}</span>
        </div>
      ))}
    </div>
  )
}

function PieTooltip({
  active,
  payload,
}: { active?: boolean; payload?: Array<{ name: string; value: number; payload: { fill: string } }> }) {
  if (!active || !payload?.length) return null
  const data = payload[0]
  return (
    <div className="rounded-lg border border-border/50 bg-background px-3 py-2 text-xs shadow-xl">
      <div className="flex items-center gap-2">
        <div className="h-2 w-2 rounded-full" style={{ backgroundColor: data.payload.fill }} />
        <span className="text-muted-foreground">{data.name}:</span>
        <span className="font-medium">{data.value}%</span>
      </div>
    </div>
  )
}

export function GeneratedDashboard() {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-semibold">Generated Dashboard</h2>
          <p className="text-sm text-muted-foreground">Business performance overview</p>
        </div>
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <div className="h-2 w-2 rounded-full bg-green-500 animate-pulse" />
          Live data
        </div>
      </div>

      {/* Metric Cards */}
      <div className="grid grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs text-muted-foreground">Total Revenue</p>
                <p className="text-2xl font-bold">$43,900</p>
                <div className="flex items-center gap-1 mt-1">
                  <TrendingUp className="h-3 w-3 text-green-500" />
                  <span className="text-xs text-green-500">+12.5%</span>
                </div>
              </div>
              <div className="h-10 w-10 rounded-lg bg-accent/20 flex items-center justify-center">
                <DollarSign className="h-5 w-5 text-accent" />
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs text-muted-foreground">Active Users</p>
                <p className="text-2xl font-bold">8,234</p>
                <div className="flex items-center gap-1 mt-1">
                  <TrendingUp className="h-3 w-3 text-green-500" />
                  <span className="text-xs text-green-500">+8.2%</span>
                </div>
              </div>
              <div className="h-10 w-10 rounded-lg bg-accent/20 flex items-center justify-center">
                <Users className="h-5 w-5 text-accent" />
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs text-muted-foreground">Orders</p>
                <p className="text-2xl font-bold">1,429</p>
                <div className="flex items-center gap-1 mt-1">
                  <TrendingDown className="h-3 w-3 text-red-500" />
                  <span className="text-xs text-red-500">-3.1%</span>
                </div>
              </div>
              <div className="h-10 w-10 rounded-lg bg-accent/20 flex items-center justify-center">
                <ShoppingCart className="h-5 w-5 text-accent" />
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs text-muted-foreground">Conversion</p>
                <p className="text-2xl font-bold">3.24%</p>
                <div className="flex items-center gap-1 mt-1">
                  <TrendingUp className="h-3 w-3 text-green-500" />
                  <span className="text-xs text-green-500">+0.4%</span>
                </div>
              </div>
              <div className="h-10 w-10 rounded-lg bg-accent/20 flex items-center justify-center">
                <Activity className="h-5 w-5 text-accent" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Charts Row 1 */}
      <div className="grid grid-cols-2 gap-6">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base">Revenue vs Target</CardTitle>
            <CardDescription>Monthly performance comparison</CardDescription>
          </CardHeader>
          <CardContent>
            <ChartContainer
              config={{
                revenue: { label: "Revenue", color: "#6366f1" },
                target: { label: "Target", color: "#404040" },
              }}
              className="h-[250px] w-full"
            >
              <AreaChart data={revenueData} accessibilityLayer>
                <CartesianGrid strokeDasharray="3 3" stroke="#333" />
                <XAxis dataKey="month" stroke="#666" fontSize={12} tickLine={false} axisLine={false} />
                <YAxis stroke="#666" fontSize={12} tickLine={false} axisLine={false} />
                <Tooltip content={<CustomTooltip />} />
                <Area
                  type="monotone"
                  dataKey="target"
                  stroke="var(--color-target)"
                  fill="var(--color-target)"
                  fillOpacity={0.3}
                  name="Target"
                />
                <Area
                  type="monotone"
                  dataKey="revenue"
                  stroke="var(--color-revenue)"
                  fill="var(--color-revenue)"
                  fillOpacity={0.5}
                  name="Revenue"
                />
              </AreaChart>
            </ChartContainer>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base">User Activity</CardTitle>
            <CardDescription>Daily active and new users</CardDescription>
          </CardHeader>
          <CardContent>
            <ChartContainer
              config={{
                active: { label: "Active Users", color: "#22c55e" },
                new: { label: "New Users", color: "#6366f1" },
              }}
              className="h-[250px] w-full"
            >
              <BarChart data={userActivityData} accessibilityLayer>
                <CartesianGrid strokeDasharray="3 3" stroke="#333" />
                <XAxis dataKey="day" stroke="#666" fontSize={12} tickLine={false} axisLine={false} />
                <YAxis stroke="#666" fontSize={12} tickLine={false} axisLine={false} />
                <Tooltip content={<CustomTooltip />} />
                <Bar dataKey="active" fill="var(--color-active)" radius={[4, 4, 0, 0]} name="Active Users" />
                <Bar dataKey="new" fill="var(--color-new)" radius={[4, 4, 0, 0]} name="New Users" />
              </BarChart>
            </ChartContainer>
          </CardContent>
        </Card>
      </div>

      {/* Charts Row 2 */}
      <div className="grid grid-cols-3 gap-6">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base">Traffic Sources</CardTitle>
            <CardDescription>Where your visitors come from</CardDescription>
          </CardHeader>
          <CardContent>
            <ChartContainer
              config={{
                Organic: { label: "Organic", color: "#6366f1" },
                Direct: { label: "Direct", color: "#22c55e" },
                Referral: { label: "Referral", color: "#f59e0b" },
                Social: { label: "Social", color: "#ec4899" },
              }}
              className="h-[200px] w-full"
            >
              <PieChart accessibilityLayer>
                <Pie
                  data={trafficSourceData}
                  cx="50%"
                  cy="50%"
                  innerRadius={50}
                  outerRadius={80}
                  dataKey="value"
                  nameKey="name"
                >
                  {trafficSourceData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.fill} />
                  ))}
                </Pie>
                <Tooltip content={<PieTooltip />} />
              </PieChart>
            </ChartContainer>
            <div className="grid grid-cols-2 gap-2 mt-4">
              {trafficSourceData.map((item) => (
                <div key={item.name} className="flex items-center gap-2">
                  <div className="h-2 w-2 rounded-full" style={{ backgroundColor: item.fill }} />
                  <span className="text-xs text-muted-foreground">{item.name}</span>
                  <span className="text-xs font-medium ml-auto">{item.value}%</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card className="col-span-2">
          <CardHeader className="pb-2">
            <CardTitle className="text-base">Conversion Funnel</CardTitle>
            <CardDescription>Weekly visitor to purchase journey</CardDescription>
          </CardHeader>
          <CardContent>
            <ChartContainer
              config={{
                visitors: { label: "Visitors", color: "#666" },
                signups: { label: "Signups", color: "#6366f1" },
                purchases: { label: "Purchases", color: "#22c55e" },
              }}
              className="h-[200px] w-full"
            >
              <LineChart data={conversionData} accessibilityLayer>
                <CartesianGrid strokeDasharray="3 3" stroke="#333" />
                <XAxis dataKey="week" stroke="#666" fontSize={12} tickLine={false} axisLine={false} />
                <YAxis stroke="#666" fontSize={12} tickLine={false} axisLine={false} />
                <Tooltip content={<CustomTooltip />} />
                <Line
                  type="monotone"
                  dataKey="visitors"
                  stroke="var(--color-visitors)"
                  strokeWidth={2}
                  dot={false}
                  name="Visitors"
                />
                <Line
                  type="monotone"
                  dataKey="signups"
                  stroke="var(--color-signups)"
                  strokeWidth={2}
                  dot={false}
                  name="Signups"
                />
                <Line
                  type="monotone"
                  dataKey="purchases"
                  stroke="var(--color-purchases)"
                  strokeWidth={2}
                  dot={false}
                  name="Purchases"
                />
              </LineChart>
            </ChartContainer>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
