// angular/src/app/pages/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { GeneratedDashboardComponent } from '../../components/generated-dashboard/generated-dashboard.component';

@Component({
  selector: 'app-dashboard',
  imports: [GeneratedDashboardComponent],
  template: `
    <div class="min-h-screen flex flex-col">
      <main class="flex-1 p-6">
        <div class="max-w-7xl mx-auto">
          <app-generated-dashboard />
        </div>
      </main>
    </div>
  `,
})
export class DashboardComponent {}

// react/app/dashboard/page.tsx
import { GeneratedDashboard } from "@/components/generated-dashboard";

export default function DashboardPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <main className="flex-1 p-6">
        <div className="max-w-7xl mx-auto">
          <GeneratedDashboard />
        </div>
      </main>
    </div>
  );
}
