// react/app/pricing/page.tsx
"use client"

import {
  EmbedProvider,
  SchematicEmbed,
} from "@schematichq/schematic-components";
import { useSchematicIsPending } from "@schematichq/schematic-react";
import React, { useEffect, useState } from "react";

export default function PlanPage() {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [accessToken, setAccessToken] = useState<string | null>(null);
  const isPending = useSchematicIsPending();

  const fetchAccessToken = async () => {
    setIsLoading(true);
    try {
      const response = await fetch("/api/accessToken");
      const result = await response.json();
      if ("accessToken" in result) {
        setAccessToken(result.accessToken);
      }
      setError(null);
    } catch (error) {
      console.error(error);
      setError("Error fetching data");
      setAccessToken(null);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchAccessToken();
  }, []);

  const componentId = process.env.NEXT_PUBLIC_SCHEMATIC_PRICING_TABLE_ID;
  if (!componentId) {
    console.error(
      "Missing Schematic component ID (NEXT_PUBLIC_SCHEMATIC_COMPONENT_ID)",
    );

    return <div>Not found</div>;
  }

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background">
        <div className="container mx-auto px-6 py-4">
          <h1 className="text-2xl font-bold mb-4">Usage & Plan</h1>
          Loading...
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-background">
        <div className="container mx-auto px-6 py-4">
          <h1 className="text-2xl font-bold mb-4">Usage & Plan</h1>
          <p>{error ?? "Unknown error"}</p>
        </div>
      </div>
    );
  }

  if (!accessToken) {
    return (
      <></>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-6 py-4">
        <EmbedProvider debug>
          <h1 className="text-2xl font-bold mb-4">Usage & Plan</h1>
          {isPending && (
            <p className="text-muted-foreground animate-pulse mb-2">
              Schematic SDK loading...
            </p>
          )}
          <SchematicEmbed accessToken={accessToken} id={componentId} />
        </EmbedProvider>
      </div>
    </div>
  )
}

// angular/src/app/pages/pricing/pricing.component.ts
import { Component, inject, OnInit, signal, computed } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { SchematicService } from '@schematichq/schematic-angular';
import { SchematicApiService } from '../../services/schematic-api.service';
import { SchematicEmbedComponent } from '../../components/schematic-embed/schematic-embed.component';
import { environment } from '../../../environments/environment.development';

/**
 * SIGNAL PATTERN: Uses Angular signals for loading/token state
 * and toSignal() for Schematic SDK observables.
 */
@Component({
  selector: 'app-pricing',
  imports: [SchematicEmbedComponent],
  template: `
    <div class="min-h-screen bg-background">
      <div class="container mx-auto px-6 py-4">
        <h1 class="text-2xl font-bold mb-4">Pricing</h1>

        @if (isLoading()) {
          <p class="text-muted-foreground">Loading...</p>
        } @else if (error()) {
          <p class="text-destructive">{{ error() }}</p>
        } @else if (accessToken()) {
          <!-- Signal pattern: isPending as a signal -->
          @if (isPending()) {
            <p class="text-muted-foreground animate-pulse mb-2">
              Schematic SDK loading...
            </p>
          }
          <app-schematic-embed
            [accessToken]="accessToken()"
            [componentId]="componentId"
          />
        }
      </div>
    </div>
  `,
})
export class PricingComponent implements OnInit {
  private api = inject(SchematicApiService);
  private schematic = inject(SchematicService);

  // Signal pattern: all state as signals
  accessToken = signal<string | null>(null);
  isLoading = signal(true);
  error = signal<string | null>(null);
  componentId = environment.schematicPricingTableId;

  // Signal pattern: convert isPending$ observable to signal
  isPending = toSignal(this.schematic.isPending$(), { initialValue: true });

  ngOnInit(): void {
    this.api.getAccessToken().subscribe({
      next: (res) => {
        this.accessToken.set(res.accessToken);
        this.isLoading.set(false);
      },
      error: (err) => {
        console.error('Error fetching access token:', err);
        this.error.set('Error fetching data');
        this.isLoading.set(false);
      },
    });
  }
}
